corpus:
  type: "single_file"
  params:
    path: "assets/data/pyzen.txt"
engine:
  dst: "assets/trained/pyzen_bow"
  type: "bow"
  params:
    preprocessor:
      type: "simple"
    vectorizer:
      type: "tfidf"
